CREATE TABLE pokemons (
	id,
	nom TEXT,
	PRIMARY KEY(id)
);

CREATE TABLE evolue_en (
	pokemon_base_id int NOT NULL,
	pokemon_evol_id int NOT NULL,
	niveau int NOT NULL,
	FOREIGN KEY(pokemon_base_id) REFERENCES pokemons(id),
	FOREIGN KEY(pokemon_evol_id) REFERENCES pokemons(id)
);

CREATE TABLE types (
	id SERIAL NOT NULL,
	libelle varchar(10) NOT NULL,
	PRIMARY KEY(id)
);



CREATE TABLE est_type (
	pokemon_id int NOT NULL,
	type_id int NOT NULL,
	FOREIGN KEY(pokemon_id) REFERENCES pokemons(id),
	FOREIGN KEY(type_id) REFERENCES types(id)
);
	
CREATE TABLE dresseurs (
	id SERIAL NOT NULL,
	nom varchar(25) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE detient_pokemons (
	dresseur_id int NOT NULL, 
	pokemon_id int NOT NULL,  
	niveau int NOT NULL,
	FOREIGN KEY(dresseur_id) REFERENCES dresseurs(id),
	FOREIGN KEY(pokemon_id) REFERENCES pokemons(id)
);

CREATE TABLE attaques (
	id SERIAL NOT NULL,
	libelle varchar(50) NOT NULL,
	type_id int NOT NULL,
	pp int NOT NULL,
	puissance int NULL,
	precision int NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(type_id) REFERENCES types(id)
);

INSERT INTO pokemons (id, nom) VALUES
	(  1, 'Bulbizarre'),
	(  2, 'Herbizarre'),
	(  3, 'Florizarre'),
	(  4, 'Salameche'),
	(  5, 'Reptincel'),
	(  6, 'Dracaufeu'),
	(  7, 'Carapuce'),
	(  8, 'Carabaffe'),
	(  9, 'Tortank'),
	( 10, 'Chenipan'),
	( 11, 'Chrysacier'),
	( 12, 'Papilusion'),
	( 13, 'Aspicot'),
	( 14, 'Coconfort'),
	( 15, 'Dardargnan'),
	( 16, 'Roucool'),
	( 17, 'Roucoups'),
	( 18, 'Roucarnage'),
	( 19, 'Rattata'),
	( 20, 'Rattatac'),
	( 21, 'Piafabec'),
	( 22, 'Rapasdepic'),
	( 23, 'Abo'),
	( 24, 'Arbok'),
	( 25, 'Pikachu'),
	( 26, 'Raichu'),
	( 27, 'Sabelette'),
	( 28, 'Sablaireau'),
	
	( 29, 'NidoranF'),
	( 30, 'Nidorina'),
	( 31, 'Nidoqueen'),
	
	( 32, 'NidoranM'),
	( 33, 'Nidorino'),
	( 34, 'Nidoking'),
	( 35, 'Melofee'),
	( 36, 'Melodelfe'),
	( 37, 'Goupix'),
	( 38, 'Feunard'),
	( 39, 'Rondoudou'),
	( 40, 'Grodoudou'),
	( 41, 'Nosferapti'),
	( 42, 'Nosferalto'),
	( 43, 'Mystherbe'),
	( 44, 'Ortide'),
	( 45, 'Rafflesia'),
	( 46, 'Paras'),
	( 47, 'Parasect'),
	( 48, 'Mimitoss'),
	( 49, 'Aeromite'),
	( 50, 'Taupiqueur'),
	( 51, 'Triopikeur'),
	( 52, 'Miaouss'),
	( 53, 'Persian'),
	( 54, 'Psykokwak'),
	( 55, 'Akwakwak'),
	( 56, 'Ferosinge'),
	( 57, 'Colossinge'),
	( 58, 'Caninos'),
	( 59, 'Arcanin'),
	( 60, 'Ptitard'),
	( 61, 'Tetarte'),
	( 62, 'Tartard'),
	( 63, 'Abra'),
	( 64, 'Kadabra'),
	( 65, 'Alakazam'),
	( 66, 'Machoc'),
	( 67, 'Machopeur'),
	( 68, 'Mackogneur'),
	( 69, 'Chetiflor'),
	( 70, 'Boustiflor'),
	( 71, 'Empiflor'),
	( 72, 'Tentacool'),
	( 73, 'Tentacruel'),
	( 74, 'Racaillou'),
	( 75, 'Gravalanch'),
	( 76, 'Grolem'),
	( 77, 'Ponyta'),
	( 78, 'Galopa'),
	( 79, 'Ramoloss'),
	( 80, 'Flagadoss'),
	( 81, 'Magneti'),
	( 82, 'Magneton'),
	( 83, 'Canarticho'),
	( 84, 'Doduo'),
	( 85, 'Dodrio'),
	( 86, 'Otaria'),
	( 87, 'Lamantine'),
	( 88, 'Tadmorv'),
	( 89, 'Grotadmorv'),
	( 90, 'Kokiyas'),
	( 91, 'Crustabri'),
	( 92, 'Fantominus'),
	( 93, 'Spectrum'),
	( 94, 'Ectoplasma'),
	( 95, 'Onix'),
	( 96, 'Soporifik'),
	( 97, 'Hypnomade'),
	( 98, 'Krabby'),
	( 99, 'Krabboss'),
	(100, 'Voltorbe'),
	(101, 'Electrode'),
	(102, 'Noeunoeuf'),
	(103, 'Noadkoko'),
	(104, 'Osselait'),
	(105, 'Ossatueur'),
	(106, 'Kicklee'),
	(107, 'Tygnon'),
	(108, 'Excelangue'),
	(109, 'Smogo'),
	(110, 'Smogogo'),
	(111, 'Rhinocorne'),
	(112, 'Rhinoferos'),
	(113, 'Leveinard'),
	(114, 'Saquedeneu'),
	(115, 'Kangourex'),
	(116, 'Hypotrempe'),
	(117, 'Hypocean'),
	(118, 'Poissirene'),
	(119, 'Poissoroy'),
	(120, 'Stari'),
	(121, 'Staross'),
	(122, 'M. Mime'),
	(123, 'Insecateur'),
	(124, 'Lippoutou'),
	(125, 'Elektek'),
	(126, 'Magmar'),
	(127, 'Scarabrute'),
	(128, 'Tauros'),
	(129, 'Magicarpe'),
	(130, 'Leviator'),
	(131, 'Lokhlass'),
	(132, 'Metamorph'),
	(133, 'Evoli'),
	(134, 'Aquali'),
	(135, 'Voltali'),
	(136, 'Pyroli'),
	(137, 'Porygon'),
	(138, 'Amonita'),
	(139, 'Amonistar'),
	(140, 'Kabuto'),
	(141, 'Kabutops'),
	(142, 'Ptera'),
	(143, 'Ronflex'),
	(144, 'Artikodin'),
	(145, 'Electhor'),
	(146, 'Sulfura'),
	(147, 'Minidraco'),
	(148, 'Draco'),
	(149, 'Dracolosse'),
	(150, 'Mewtwo'),
	(151, 'Mew');

INSERT INTO types (id, libelle) VALUES 
	(  1, 'Combat'),
	(  2, 'Dragon'),
	(  3, 'Eau'),
	(  4, 'Electrique'),
	(  5, 'Feu'),
	(  6, 'Glace'),
	(  7, 'Insecte'),
	(  8, 'Normal'),
	(  9, 'Plante'),
	( 10, 'Poison'),
	( 11, 'Psy'),
	( 12, 'Roche'),
	( 13, 'Sol'),
	( 14, 'Spectre'),
	( 15, 'Vol');
